### ISSUE TITLE
cannot handle circular flows

### ISSUE THREAD

**Issue by christopherlam** [kurkle/chartjs-chart-sankey#1]
Hi!
I'm a commiter in https://github.com/Gnucash/gnucash/ and keen to import this nice module for cash flow charts. I hope you wouldn't mind? It'd need to wait for chartJS-3 release first.
One issue:  it doesn't seem to sanity check for circular flows?
```js
{ from:"A", to:"B", flow:10 },
{ from:"B", to:"C", flow:10 },
{ from:"C", to:"A", flow:10 }
```

**Comment by kurkle** [comment]
No, I would not mind :)

Initial support for circular flows added in just released v0.1.4
The result can be improved, but at least it does not loop forever.

![image](https://user-images.githubusercontent.com/27971921/87775665-23ed6500-c82f-11ea-8a90-694400d91214.png)

**Comment by christopherlam** [comment]
Thanks!

Here's a sneek peek:
![image](https://user-images.githubusercontent.com/1975870/87788244-914bc680-c82c-11ea-88f5-395f7aca3854.png)

**Comment by christopherlam** [comment]
I think this issue https://github.com/kurkle/chartjs-chart-sankey/issues/1 may considered fixed. Looks like chartJS 3 is still in heavy flux, and thus cannot be merged into gnucash until it's out of beta. Therefore a sankey cashflow chart cannot be merged in yet. It may need to wait for 5.0 due sometime in 2022. https://wiki.gnucash.org/wiki/Release_Schedule

**Comment by christopherlam** [comment]
P.S. WebkitGTK has stopped supporting Windows users. GnuCash uses itfor reports and charts. This means it can use webkit2 on linux, but needs to use webkit1 on mac+windows. Thankfully chartjs runs fairly well on webkit1. I note this project uses some modern javascript, which works well, but we may need to port them to older javascript to be usable in webkit1. So, once chartjs-3 is finalized, and this module is stable, we may need to ask for help occasionally in the future :) Example: https://github.com/Gnucash/gnucash/commit/555a467aba7733e9bf7d6e53cc5b1054c328427a

//not a native js hacker
//there may be errors in my interpretation as above
@jralls and @gjanssens, lead gnucash devs aren't either
