### ISSUE TITLE
Changing font color

### ISSUE THREAD

**Issue by Frohrer** [kurkle/chartjs-chart-sankey#10]
Hello, is it possible to change the default font color?
I have tried various ways, for example setting `Chart.defaults.color = '#fffff';` and changing the color in the dataset option (but this only changes the label at the top.

Thank you for developing this plugin.

**Comment by Frohrer** [comment]
I edited the source and re-built. Closing.

**Comment by kurkle** [comment]
Re-opened, because this is a valid and probably common need. Care to share your changes?

**Comment by Frohrer** [comment]
Edit the function _drawlabels(): in src/controller.js and replace ctx.fillStyle = 'black' with whatever font color you need. 

```	
_drawLabels() {
		const me = this;
		const ctx = me._ctx;
		const nodes = me._nodes || new Map();
		const {xScale, yScale} = me._cachedMeta;

		ctx.save();
		const chartArea = me.chart.chartArea;

		for (const node of nodes.values()) {
			const x = xScale.getPixelForValue(node.x);
			const y = yScale.getPixelForValue(node.y);
			const max = Math.max(node.in, node.out);
			const height = Math.abs(yScale.getPixelForValue(node.y + max) - y);
			ctx.fillStyle = '[COLOR]';
			ctx.textBaseline = 'middle';
			if (x < chartArea.width / 2) {
				ctx.textAlign = 'left';
				ctx.fillText(node.key, x + 15, y + height / 2);
			} else {
				ctx.textAlign = 'right';
				ctx.fillText(node.key, x - 5, y + height / 2);
			}
		}
		ctx.restore();
	}
```
