### ISSUE TITLE
Overlapping nodes for some datasets

### ISSUE THREAD

**Issue by bofa** [kurkle/chartjs-chart-sankey#106]
Thanks for a very useful extension of chartjs. I have been running in to issues with overlapping nodes for a lot of datasets when trying it out. Example bellow. Though I can report it and see if others have similar issues.

![image](https://github.com/kurkle/chartjs-chart-sankey/assets/3724917/c192d962-1e8c-49b7-8739-8f89ad384945)

**Comment by uberhus** [comment]
I have a similar issue here, where the "Unsold 2", "Unsold 3" and "Unsold 4" overalap with other nodes. I tried to resolve this by setting priorities, but if you remove the // from priority you'll see that the overlap just gets worse: https://codepen.io/Yli-T/pen/OJGXwKg

I wonder if there is any way to resolve this with current options?

**Comment by kurkle** [comment]
Does not look right to me. Can you provide a config or a codepen to reproduce?

**Comment by bofa** [comment]
One dataset creating the issues on my end is
```json
[
    {
      "from": "115 ",
      "to": "AA",
      "flow": 5
    },
    {
      "from": "115 ",
      "to": "BB",
      "flow": 4
    },
    {
      "from": "115 ",
      "to": "CC",
      "flow": 4
    },
    {
      "from": "29  ",
      "to": "DD",
      "flow": 4
    },
    {
      "from": "110 ",
      "to": "EE",
      "flow": 3
    },
    {
      "from": "AA",
      "to": "XX",
      "flow": 5
    },
    {
      "from": "BB",
      "to": "XX",
      "flow": 4
    },
    {
      "from": "CC",
      "to": "YY",
      "flow": 4
    },
    {
      "from": "DD",
      "to": "XX",
      "flow": 4
    },
    {
      "from": "EE",
      "to": "XX",
      "flow": 3
    }
  ]
```

**Comment by bofa** [comment]
Was the issue reproducible?

**Comment by kurkle** [comment]
Not in my current dev branch (not in gh yet). But it's a work in progress still.
I'll verify in main too.

**Comment by bofa** [comment]
It's all working now. Thank you.
