### ISSUE TITLE
custom keys not fully supported

### ISSUE THREAD

**Issue by Ribeiro-Tiago** [kurkle/chartjs-chart-sankey#116]
The key customization from [parsing prop](https://github.com/kurkle/chartjs-chart-sankey/blob/main/src/controller.js#L84) is not fully supported

Using custom keys my charts were not loading correctly and tooltip was just showing `undefined -> undefined: undefined`

**Comment by MarcBaeuerle** [comment]
not a fix but a temporary solution for the `undefined -> undefined: undefined` for me was to include 

```
options: {
  plugins: {
    tooltip: {
      callbacks: {
        title(context) {
          context = context[0];
          const labels = context.dataset.labels;
          const item = context.dataset.data[context.dataIndex];
          return labels[item.source] + ' -> ' + labels[item.target];
        },
        label(context) {
          const item = context.dataset.data[context.dataIndex];
          return item.value + ' connections';
        }
      },
    },
  },
}
```
where I used the following 
```
parsing: {
  from: 'source',
  to: 'target',
  flow: 'value'
},
```
