### ISSUE TITLE
Tooltip settings

### ISSUE THREAD

**Issue by nassissme** [kurkle/chartjs-chart-sankey#22]
Hi ! 

I cannot set the tooltip options. I'm trying to disable them to display a custom tooltip (using the external attribute). 

Here is an [example](https://codesandbox.io/s/test-tooltip-g9xq0?file=/src/index.js).

How can I configure custom (external) tooltips?

**Comment by kurkle** [comment]
plugin options go in `config.options.plugins` and inline plugins go in `confing.plugins`. So you are missing the `options` in your example.

**Comment by nassissme** [comment]
Ho yes thanks !
