### ISSUE TITLE
Multine for labels

### ISSUE THREAD

**Issue by nassissme** [kurkle/chartjs-chart-sankey#23]
Hi ! 

I need to have a title and a subtitle on a node.

Example: 

![github_issue](https://user-images.githubusercontent.com/7334988/115552332-7d962a80-a2ac-11eb-85d4-052203a212df.png)

I saw that with `fillText` you can't do multi-line. 

Is there a way to do this? If not, can we consider changing the '`labels`' parameter or adding a new '`subtitles`' parameter.

Thx.

**Comment by kurkle** [comment]
Yes, it can be considered, looks like a common use case. Just multiple lines is probably not enough, you'd want to style them separately too, right?

**Comment by nassissme** [comment]
Yes, it could be interesting, how do you think you could do it?
