### ISSUE TITLE
Refresh problem when updating data

### ISSUE THREAD

**Issue by nassissme** [kurkle/chartjs-chart-sankey#29]
Hi ! 

I am implementing sankey diagrams on a project. I have a great result, thanks for this project! 

However, there is a refresh problem when I update the data, especially when I reduce the data of all the nodes. 

I made an example here : https://codesandbox.io/s/update-data-j3rvy?file=/src/index.js

![sankey_issue](https://user-images.githubusercontent.com/7334988/119156894-f37ce580-ba54-11eb-80e9-ac6523158656.gif)

The size of the nodes is very small, while there is space to draw them higher. 

I found a way around the problem by making two calls to the update() function (which is not very nice).

I tried to look in the code without finding the problem. 

Can you help me to find a fix? 

Thanks for your help.

**Comment by jledentu** [comment]
@kurkle It seems that there is an issue on how the `max` is set on scales?

In the `determineDataLimits` function of Chart.js, new `max` values are not taken into account (`_userMax` still reflects the previous max value).

**Comment by kurkle** [comment]
@jledentu correct. Trying to decide what would be the correct fix for this. It might be better to fix this in core (too?), because the scales are updated before data is parsed. `scale.confugure` is called again after elements have been resynced (and data parsed), so that would be the correct spot to store the _userMin etc.

**Comment by jledentu** [comment]
Can be closed (fixed by #32). @kurkle Do you plan a new npm release soon?

**Comment by kurkle** [comment]
Released 0.6.0

**Comment by nassissme** [comment]
Thanks a lot !
