### ISSUE TITLE
Priorities issue

### ISSUE THREAD

**Issue by OverSamu** [kurkle/chartjs-chart-sankey#45]
Hi

Data: `[{
  from: 'TEST1', to: 'TEST2', flow: 15},
  {from: 'TEST3', to: 'TEST2', flow: 20},
  {from: 'TEST4', to: 'TEST2', flow: 25},
  {from: 'TEST4', to: 'TEST5', flow: 25},
  {from: 'TEST2', to: 'TEST6', flow: 60},
  {from: 'TEST5', to: 'TEST6', flow: 25},
  {from: 'TEST7', to: 'TEST6', flow: 25}]`

Priorities: `{
  TEST1: 1,
  TEST2: 1,
  TEST3: 2,
  TEST4: 3,
  TEST5: 2,
  TEST6: 1,
  TEST7: 4
}`

![test1](https://user-images.githubusercontent.com/17676511/127877967-20770170-45c9-4036-b938-ae1894ccb156.jpg)

Priorities: `{
  TEST1: 2,
  TEST2: 1,
  TEST3: 3,
  TEST4: 4,
  TEST5: 2,
  TEST6: 1,
  TEST7: 1
}`

![test2](https://user-images.githubusercontent.com/17676511/127877990-0c3447a1-085a-41e4-ab9a-44046baad354.jpg)

Why does this happen?
The TEST2 node should leave free space for the connection between the TEST7 and TEST6 nodes.

Thanks in advance

**Comment by shlokshah-dev** [comment]
Hi @OverSamu,

I know this is a bit unrelated to the issue you raised. But I'm trying to figure out to add a tooltip or a label to the links to indicate the value of the flow. Do you think you could help me in the same?

Thanks

**Comment by OverSamu** [comment]
> I know this is a bit unrelated to the issue you raised. But I'm trying to figure out to add a tooltip or a label to the links to indicate the value of the flow for one of my projects. Do you think you could help me in the same?

Hi @shlokshah-dev 
I think what you wrote has already been asked here: https://github.com/kurkle/chartjs-chart-sankey/issues/38

**Comment by kurkle** [comment]
Looks like a bug
