### ISSUE TITLE
Update examples a bit

### ISSUE THREAD

**Issue by ddelrio1986** [kurkle/chartjs-chart-sankey#5]
I created an example of how to use this plugin with webpack imports and also an example of how to integrate it with Vue.js 2. I was wondering the best way to incorporate this into the README.md?

https://codesandbox.io/s/reverent-boyd-od2fr?file=/src/App.vue

![Vue_js_2___Chart_js_3___Sankey_Diagram_-_CodeSandbox](https://user-images.githubusercontent.com/58251/93376579-cf169c80-f827-11ea-8b1a-5a027e78c9e5.png)

**Comment by kurkle** [comment]
Maybe just add link to it?

**Comment by kurkle** [comment]
Added to readme: https://github.com/kurkle/chartjs-chart-sankey/commit/f0a04527ef45bbce81527ac58eca582b07c1acfd
