### ISSUE TITLE
Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by ritvik-statsig** [kurkle/chartjs-chart-sankey#56]
When I try to register the SankeyController, I get "Cannot read property 'prototype' of undefined". Here is a code snippet:

```
import type { ChartDataset, ChartOptions } from 'chart.js';
import { Chart } from 'chart.js';
import { SankeyController, Flow } from 'chartjs-chart-sankey';

Chart.register(SankeyController, Flow);
```

Would appreciate some help! Thanks!

**Comment by kurkle** [comment]
What version of chart.js are you using?

**Comment by kurkle** [comment]
One of the samples using typescript, seems to work fine:
https://codesandbox.io/s/compassionate-carson-ne1kn?file=/src/index.ts

**Comment by ritvik-statsig** [comment]
This seems to be something weird going on with the import not being done before the register - if I move the register later (to within a react component) it's all fine.

**Comment by jmtimko5** [comment]
I am also seeing this issue in Chart.js 3.5.1
