### ISSUE TITLE
Removing x-axis offsets hides right-most nodes

### ISSUE THREAD

**Issue by rubenlopezlozoya** [kurkle/chartjs-chart-sankey#6]
I was wondering if there is any way of avoiding the X scale offset without having the right most nodes disappearing. If I do not set the scales.x.offset property tu false this is what I see:
![image](https://user-images.githubusercontent.com/23010951/94257504-3e535700-fee0-11ea-8d75-49f0b47ad63e.png)

However, when I set the property to false, the offset is removed but the right most nodes too:
![image](https://user-images.githubusercontent.com/23010951/94257590-5f1bac80-fee0-11ea-8939-6dcbf1573ee3.png)

Thanks for the chart, it is really impressive.

**Comment by kurkle** [comment]
There is a hacky workaround (values needed depends on the number of nodes):
```js
  options: {
    scales: {
      x: {
        min: 0.05,
        ticks: {
          stepSize: 0.1
        }
      }
    },
  }
```
[Pen](https://codepen.io/kurkle/pen/yLOwRJg)

**Comment by kurkle** [comment]
Pushed v0.1.6 that should have fixed this. You'll need to include some layout padding for the nodes to fit still:
```js
options: {
  scales: {
    x: {
      offset: false
    }
  },
  layout: {
    padding: {
      right: 11
    }
  }
}
```

**Comment by rubenlopezlozoya** [comment]
Thanks a lot! It works now.
