### ISSUE TITLE
x axis position of items

### ISSUE THREAD

**Issue by seven700** [kurkle/chartjs-chart-sankey#64]
Is it possible to specific the order of items along the x axis? For example having a node start further along the sankey diagram rather than at the far left, or having a node finish midway rather than at the far right?

For example. is it possible to force 'banana' to be in the same x axis position as fossil fuels and electricity?

![image](https://user-images.githubusercontent.com/57974394/157296560-38e33879-d30c-479a-b9b5-9ad10705d045.png)

**Comment by kurkle** [comment]
Was not possible, but also was easy to implement.
So with 0.9.0 you'd add (to dataset):

```js
column: {
  Banana: 1
}
```

Columns are integers starting from `0` at left and going in increments of one.
There are quite a few limitations on how you can define the columns.. I guess it will be fine-tuned in the future.
