### ISSUE TITLE
Issue with IE 11 : Object doesn't support property or method 'values'

### ISSUE THREAD

**Issue by kirancheema** [kurkle/chartjs-chart-sankey#8]
Hello Just FYI the following errors occurs with IE 11 

![image](https://user-images.githubusercontent.com/9959732/95062805-5e132800-06f5-11eb-8e19-6e1ccaa50ec6.png)

**Comment by kurkle** [comment]
Sorry for the late response, I have no plans on supporting IE11 since this is based on Chart.js v3 that itself does not support IE11.
