### ISSUE TITLE
Configurable columns length

### ISSUE THREAD

**Issue by Mihailoff** [kurkle/chartjs-chart-sankey#82]
The current `column` config behaviour is a bit confusing. With the config below my expectation was that it will define 4 columns prior to the 5th "Energy".

```
datasets: [
  {
    data: [
      { from: "Oil", to: "Energy", flow: 15 },
      { from: "Natural Gas", to: "Energy", flow: 20 },
      { from: "Coal", to: "Energy", flow: 25 },
      { from: "Electricity", to: "Energy", flow: 25 },
    ],
    column: {
      "Oil": 0,
      "Natural Gas": 1,
      "Coal": 2,
      "Electricity": 3,
    },
  },
]
```

After some investigation, it turns out that the count of columns is computed automatically based on the data and the actual visualization is broken.

![Screen Shot 2022-11-17 at 4 25 11 PM](https://user-images.githubusercontent.com/413295/202588690-1b221f01-3ed3-4cf9-bbdc-b416563b4127.png)

https://codesandbox.io/s/vue-js-2-chart-js-3-sankey-diagram-forked-b5ob9i?file=/src/App.vue:710-1316

**Comment by kurkle** [comment]
Probably same underlying issue with #81

**Comment by jgwillard** [comment]
Hi, I am running into this issue as well. Do you have an idea for a solution? Accepting pull requests for this? For me the issue is actually preventing the graph from rendering in the case that I define n columns and then the `calculateMaxX` function returns a value greater than n. Can provide more details if that's useful. Thanks.

**Comment by kurkle** [comment]
Pull requests are welcome!
I don't currently have a clue about the solution. First thought would be to use the provided columns instead of automatic - but that might need some refactoring.

**Comment by Mihailoff** [comment]
Thank you!

Is it time for a new release? (the last one was on Nov 22, 2022 [v0.12.0)](https://github.com/kurkle/chartjs-chart-sankey/releases/tag/v0.12.0)

**Comment by kurkle** [comment]
v0.12.1 was released today
